#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -eu

if [[ -f /.dockerenv ]]; then
	exit 0;
fi

make -f "$SCRIPTPATH/../build/Makefile" container-start
